spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: <put your client-id>
            client-secret: <put your client-secret here>
        provider:
          okta:
            authorization-uri: https://dev-10300395.okta.com/oauth2/v1/authorize
            token-uri: https://dev-10300395.okta.com/oauth2/v1/token
            user-info-uri: https://dev-10300395.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-10300395.okta.com/oauth2/v1/keys
